latihan/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PenyuluhController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\MajelisController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [HomeController::class, 'home']);

Route::get('/login', [LoginController::class, 'login'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'authenticate']);
Route::post('/logout', [LoginController::class, 'logout']);

Route::get('/register', [RegisterController::class, 'register'])->middleware('guest');
Route::post('/register', [RegisterController::class, 'store']);

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware('auth');

Route::resource('penyuluh', PenyuluhController::class);
Route::get('/penyuluh/search', [PenyuluhController::class, 'search']);

Route::resource('majelis', MajelisController::class);

Route::resource('jadwal', JadwalController::class);

Route::resource('laporan', LaporanController::class);

Route::resource('admin', AdminController::class);

// Route::get('/majelis', [MajelisController::class, 'index'])->name('majelis_view');
// Route::get('/majelis/create', [MajelisController::class, 'create'])->name('majelis_add');
// Route::post('/majelis/create', [MajelisController::class, 'store'])->name('majelis_add');
// Route::get('/user/show/{id}', [MajelisController::class, 'show'])->name('majelis_show');
// Route::post('/user/edit/{id}', 'UserController@edit')->name('user_edit');
// Route::post('/user/delete', 'UserController@delete')->name('user_delete');

// Route::get('/login', [AuthController::class, 'index'])->name('login');
// Route::post('/custom-signin', [AuthController::class, 'createSignin'])->name('signin.custom');


// Route::get('/register', [AuthController::class, 'signup'])->name('register');
// Route::post('/create-user', [AuthController::class, 'customSignup'])->name('user.registration');


// Route::get('/dashboard', [AuthController::class, 'dashboardView'])->name('dashboard');
// Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

latihan/app/Http/Controllers/LaporanController.php
<?php

namespace App\Http\Controllers;

use App\Models\LaporanModel;
use Illuminate\Http\Request;
use App\Models\NewMajelisModel;
use App\Models\PenyuluhModel;
use Exception;
use Illuminate\Support\Facades\DB;

class LaporanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $laporan = LaporanModel::latest()->with('majelis')->with('penyuluh')->paginate(5);


        return view('laporan.index',[
            "title" => "Laporan",
            "active" =>"laporan"
        ], compact('laporan'))
            ->with('i',(request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('laporan.create',[
            "title" => "Laporan",
            "active" =>"laporan",
            "penyuluh" => PenyuluhModel::all(),
            "majelis"=> NewMajelisModel::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'judul_laporan' => 'required',
            'isi_kegiatan' => 'required',
            'jumlah_peserta' => 'required',
            'tanggal_kegiatan' => 'required',
            'id_majelis' => 'required',
            'id_penyuluh' => 'required',
        ]);
        try {

        $laporan = new LaporanModel();
        $laporan->judul_laporan = $request->judul_laporan;
        $laporan->isi_kegiatan = $request->isi_kegiatan;
        $laporan->jumlah_peserta = $request->jumlah_peserta;
        $laporan->tanggal_kegiatan = $request->tanggal_kegiatan;
        $laporan->id_majelis = $request->id_majelis;
        $laporan->id_penyuluh = $request->id_penyuluh;
        $laporan->save();



        return redirect()->route('laporan.index')->with('success','Successfully!');

        } catch (Exception $e) {

            DB::rollback();

            return redirect()->route('laporan.index')->with('error','Failed!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\LaporanModel  $laporanModel
     * @return \Illuminate\Http\Response
     */
    public function show(LaporanModel $laporan)
    {
        return view ('laporan.show',[
            "title" => "Laporan",
            "active" =>"laporan"
        ], compact('laporan'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\LaporanModel  $laporanModel
     * @return \Illuminate\Http\Response
     */
    public function edit(LaporanModel $laporan)
    {
        return view ('laporan.edit',[
            "title" => "Laporan",
            "active" =>"laporan",
            "penyuluh" => PenyuluhModel::all(),
            "majelis"=> NewMajelisModel::all(),
        ], compact('laporan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\LaporanModel  $laporanModel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, LaporanModel $laporan)
    {

        try {

            $request->validate([
                'judul_laporan' => 'required',
                'isi_kegiatan' => 'required',
                'jumlah_peserta' => 'required',
                'tanggal_kegiatan' => 'required',
                'id_majelis' => 'required',
                'id_penyuluh' => 'required',
            ]);

            $dataLaporan = [
                'judul_laporan' => $request->judul_laporan,
                'isi_kegiatan' => $request->isi_kegiatan,
                'jumlah_peserta' => $request->jumlah_peserta,
                'tanggal_kegiatan' => $request->tanggal_kegiatan,
                'id_majelis' => $request->id_majelis,
                'id_penyuluh' => $request->id_penyuluh,
            ];

            $laporan->update($dataLaporan);

            return redirect()->route('laporan.index')->with('success','Successfully!');
        }

        catch (\Exception $e) {
            return redirect()->route('laporan.index')->with('error','Failed!');
       }



        }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\LaporanModel  $laporanModel
     * @return \Illuminate\Http\Response
     */
    public function destroy(LaporanModel $laporan)
    {
        $laporan->delete();
        return redirect()->route('laporan.index')->with('success','Successfully!');
    }
}

latihan/resources/views/laporan/create.blade.php
@extends('layouts.main')

@section('container')
    @if (session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    @if (session()->has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ session('error') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Tambah Laporan</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('laporan.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <form action="{{ route('laporan.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Penyuluh:</strong>
                    <select name="id_penyuluh">
                        @foreach ($penyuluh as $p)
                        <option value="{{ $p->id }}">{{ $p->nama }}</option>
                        @endforeach
                    </select>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Majelis:</strong>
                    <select name="id_majelis">
                        @foreach ($majelis as $m)
                        <option value="{{ $m->id }}">{{ $m->nama_majelis }}</option>
                        @endforeach
                    </select>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Judul:</strong>
                    <input type="text" name="judul_laporan" class="form-control" placeholder="Judul">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Isi:</strong>
                    <input type="text" name="isi_kegiatan" class="form-control" placeholder="Isi">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Jumlah:</strong>
                    <input type="number" name="jumlah_peserta" class="form-control" placeholder="Jumlah Peserta">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Tanggal:</strong>
                    <input type="date" name="tanggal_kegiatan" class="form-control" placeholder="">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center mt-4">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>

@endsection

latihan/resources/views/laporan/edit.blade.php
@extends('layouts.main')

@section('container')

    @if (session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    @if (session()->has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ session('loginError') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Laporan</h2>
        </div>
        <div class="pull-right mt-4">
            <a class="btn btn-primary" href="{{ route('laporan.index') }}"> Back</a>
        </div>
    </div>
</div>

<form action="{{ route('laporan.update', $laporan->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                {{-- <strong>Id User:</strong> --}}
                <input type="hidden" name="id" value="{{ $laporan->id }}" class="form-control" placeholder="id">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Penyuluh:</strong>
                <select name="id_penyuluh">
                    @foreach ($penyuluh as $p)
                    <option value="{{ $p->id }}">{{ $p->nama }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Majelis:</strong>
                <select name="id_majelis">
                    @foreach ($majelis as $m)
                    <option value="{{ $m->id }}">{{ $m->nama_majelis }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Judul</strong>
                <input type="text" name="judul_laporan"  value="{{ $laporan->judul_laporan }}" class="form-control" placeholder="Judul">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Isi:</strong>
                <input type="text" name="isi_kegiatan"  value="{{ $laporan->isi_kegiatan }}"class="form-control" placeholder="materi">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Jumlah Peserta:</strong>
                <input type="number" name="jumlah_peserta"  value="{{ $laporan->jumlah_peserta }}"class="form-control" placeholder="Jumlah Peserta">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Tanggal:</strong>
                <input type="date" name="tanggal_kegiatan"  value="{{ $laporan->tanggal_kegiatan }}"class="form-control" placeholder="">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>

@endsection

latihan/resources/views/laporan/index.blade.php
@extends('layouts.main')

@section('container')

@if (session()->has ('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ session('success') }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
@endif

@if (session()->has ('error'))
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{ session('loginError') }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
@endif

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Laporan</h2>
        </div>
        <div class="pull-right mt-5 mb-4">
            <a class="btn btn-success" href="{{ route('laporan.create') }}"> Tambah</a>
        </div>
    </div>
</div>

<form class="form" method="get" action="#">
    @csrf
    <div class="form-group w-100 mb-3">
        <label for="search" class="d-block mr-2">Pencarian</label>
        <input type="text" name="search" class="form-control w-75 d-inline" id="search" placeholder="Masukkan keyword">
        <button type="submit" class="btn btn-primary mb-1">Cari</button>
    </div>
</form>

<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Judul</th>
        <th>Nama Penyuluh</th>
        <th>Isi</th>
        <th>Jumlah Peserta</th>
        <th>Majelis</th>
        <th>Tanggal</th>
        <th width="280px">Aksi</th>
    </tr>
    @foreach ($laporan as $l)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $l->judul_laporan}}</td>
        <td>{{ $l->penyuluh->nama }}</td>
        <td>{{ $l->isi_kegiatan }}</td>
        <td>{{ $l->jumlah_peserta }}</td>
        <td>{{ $l->majelis->nama_majelis }}</td>
        <td>{{ $l->tanggal_kegiatan }}</td>
        <td>
            <form action="{{ route('laporan.destroy',$l->id) }}" method="post">

                <a class="btn btn-info" href="{{ route('laporan.show', $l->id) }}">Show</a>

                <a class="btn btn-primary" href="{{ route('laporan.edit', $l->id) }}">Edit</a>

                @csrf
                @method('DELETE')

                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </td>
    </tr>
    @endforeach
</table>

{!! $laporan->links() !!}


@endsection

latihan/resources/views/laporan/show.blade.php
@extends('layouts.main')

@section('container')

@if (session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

@if (session()->has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ session('loginError') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
@endif

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Detail Laporan</h2>
        </div>
        <div class="pull-right mt-4">
            <a class="btn btn-primary" href="{{ route('laporan.index') }}"> Back</a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>id_penyuluh:</strong>
            {{ $laporan->id_penyuluh }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>id_majelis:</strong>
            {{ $laporan->id_majelis }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>penyuluh:</strong>
            {{ $laporan->penyuluh->nama }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>majelis:</strong>
            {{ $laporan->majelis->nama_majelis }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Judul :</strong>
            {{ $laporan->judul_laporan }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Isi :</strong>
            {{ $laporan->isi_kegiatan }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Jumlah Peserta :</strong>
            {{ $laporan->jumlah_peserta }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Tanggal :</strong>
            {{ $laporan->tanggal_kegiatan }}
        </div>
    </div>
</div>

@endsection