latihan/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PenyuluhController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\MajelisController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [HomeController::class, 'home']);

Route::get('/login', [LoginController::class, 'login'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'authenticate']);
Route::post('/logout', [LoginController::class, 'logout']);

Route::get('/register', [RegisterController::class, 'register'])->middleware('guest');
Route::post('/register', [RegisterController::class, 'store']);

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware('auth');

Route::resource('penyuluh', PenyuluhController::class);
Route::get('/penyuluh/search', [PenyuluhController::class, 'search']);

Route::resource('majelis', MajelisController::class);

Route::resource('jadwal', JadwalController::class);

Route::resource('laporan', LaporanController::class);

Route::resource('admin', AdminController::class);

// Route::get('/majelis', [MajelisController::class, 'index'])->name('majelis_view');
// Route::get('/majelis/create', [MajelisController::class, 'create'])->name('majelis_add');
// Route::post('/majelis/create', [MajelisController::class, 'store'])->name('majelis_add');
// Route::get('/user/show/{id}', [MajelisController::class, 'show'])->name('majelis_show');
// Route::post('/user/edit/{id}', 'UserController@edit')->name('user_edit');
// Route::post('/user/delete', 'UserController@delete')->name('user_delete');

// Route::get('/login', [AuthController::class, 'index'])->name('login');
// Route::post('/custom-signin', [AuthController::class, 'createSignin'])->name('signin.custom');


// Route::get('/register', [AuthController::class, 'signup'])->name('register');
// Route::post('/create-user', [AuthController::class, 'customSignup'])->name('user.registration');


// Route::get('/dashboard', [AuthController::class, 'dashboardView'])->name('dashboard');
// Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

latihan/app/Http/Controllers/JadwalController.php
<?php

namespace App\Http\Controllers;

use App\Models\JadwalModel;
use App\Models\NewMajelisModel;
use App\Models\PenyuluhModel;
use Exception;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class JadwalController extends Controller
{
    public function index(Request $request) {

        $jadwal = JadwalModel::latest()->with('majelis')->with('penyuluh')->paginate(5);


        return view('jadwal.index',[
            "title" => "Jadwal",
            "active" =>"jadwal"
        ], compact('jadwal'))
            ->with('i',(request()->input('page', 1) - 1) * 5);
    }

    public function create() {

        return view ('jadwal.create',[
            "title" => "Jadwal",
            "active" =>"jadwal",
            "penyuluh" => PenyuluhModel::all(),
            "majelis"=> NewMajelisModel::all(),
        ]);
    }

    public function store(Request $request) {

        $request->validate([
            'materi' => 'required',
            'lokasi' => 'required',
            'hari_jam' => 'required',
            'id_majelis' => 'required',
            'id_penyuluh' => 'required',
        ]);

        try {

        $jadwal = new JadwalModel();
        $jadwal->materi = $request->materi;
        $jadwal->lokasi = $request->lokasi;
        $jadwal->hari_jam = date("Y-m-d H:i:s", strtotime($request->hari_jam)) ;
        $jadwal->id_majelis = $request->id_majelis;
        $jadwal->id_penyuluh = $request->id_penyuluh;
        $jadwal->save();

        return redirect()->route('jadwal.index')->with('success','Successfully!');

        } catch (Exception $e) {

            DB::rollback();

            return redirect()->route('jadwal.index')->with('error','Failed!');
        }
    }

    public function show(JadwalModel $jadwal) {

        return view ('jadwal.show',[
            "title" => "Jadwal",
            "active" =>"jadwal"
        ], compact('jadwal'));

    }

    public function edit(JadwalModel $jadwal) {

        return view ('jadwal.edit',[
            "title" => "Jadwal",
            "active" =>"jadwal",
            "penyuluh" => PenyuluhModel::all(),
            "majelis"=> NewMajelisModel::all(),
        ], compact('jadwal'));

    }

    public function update(Request $request, JadwalModel $jadwal) {

        //

        $request->validate([
            'materi' => 'required',
            'lokasi' => 'required',
            'hari_jam' => 'required',
            'id_majelis' => 'required',
            'id_penyuluh' => 'required',
        ]);

        // date("Y-m-d H:i:s", strtotime($request->hari_jam));

        $dataJadwal = [
            'materi' => $request->materi,
            'lokasi' => $request->lokasi,
            'hari_jam' => date("Y-m-d H:i:s", strtotime($request->hari_jam)),
            'id_majelis' =>  $request->id_majelis,
            'id_penyuluh' =>  $request->id_penyuluh,
        ];


        $jadwal->update($dataJadwal);

        return redirect()->route('jadwal.index')->with('success','Successfully!');

    }



    public function destroy (JadwalModel $jadwal) {

        $jadwal->delete();
        return redirect()->route('jadwal.index')->with('success','Successfully!');
    }


}

latihan/resources/views/jadwal/create.blade.php
@extends('layouts.main')

@section('container')
    @if (session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    @if (session()->has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ session('error') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Tambah Jadwal</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('jadwal.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <form action="{{ route('jadwal.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Penyuluh:</strong>
                    <select name="id_penyuluh">
                        @foreach ($penyuluh as $p)
                        <option value="{{ $p->id }}">{{ $p->nama }}</option>
                        @endforeach
                    </select>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Majelis:</strong>
                    <select name="id_majelis">
                        @foreach ($majelis as $m)
                        <option value="{{ $m->id }}">{{ $m->nama_majelis }}</option>
                        @endforeach
                    </select>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Materi:</strong>
                    <input type="text" name="materi" class="form-control" placeholder="materi">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Lokasi:</strong>
                    <input type="text" name="lokasi" class="form-control" placeholder="lokasi">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Hari Jam:</strong>
                    <input type="datetime-local" name="hari_jam" class="form-control" placeholder="hari_jam">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center mt-4">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>

@endsection

latihan/resources/views/jadwal/edit.blade.php
@extends('layouts.main')

@section('container')

    @if (session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    @if (session()->has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ session('loginError') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Penyuluh</h2>
        </div>
        <div class="pull-right mt-4">
            <a class="btn btn-primary" href="{{ route('jadwal.index') }}"> Back</a>
        </div>
    </div>
</div>

<form action="{{ route('jadwal.update',$jadwal->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                {{-- <strong>Id User:</strong> --}}
                <input type="hidden" name="id" value="{{ $jadwal->id }}" class="form-control" placeholder="id">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Penyuluh:</strong>
                <select name="id_penyuluh">
                    @foreach ($penyuluh as $p)
                    <option value="{{ $p->id }}">{{ $p->nama }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Majelis:</strong>
                <select name="id_majelis">
                    @foreach ($majelis as $m)
                    <option value="{{ $m->id }}">{{ $m->nama_majelis }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Hari Jam</strong>
                <input type="datetime-local" name="hari_jam"  value="{{ date("Y-m-d\TH:i:s", strtotime("$jadwal->hari_jam")) }}" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Materi:</strong>
                <input type="text" name="materi"  value="{{ $jadwal->materi }}"class="form-control" placeholder="materi">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Lokasi:</strong>
                <input type="text" name="lokasi"  value="{{ $jadwal->lokasi }}"class="form-control" placeholder="lokasi">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>

@endsection

latihan/resources/views/jadwal/index.blade.php
@extends('layouts.main')

@section('container')

@if (session()->has ('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ session('success') }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
@endif

@if (session()->has ('error'))
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{ session('loginError') }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
@endif

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Jadwal</h2>
        </div>
        <div class="pull-right mt-5 mb-4">
            <a class="btn btn-success" href="{{ route('jadwal.create') }}"> Tambah</a>
        </div>
    </div>
</div>

<form class="form" method="get" action="#">
    @csrf
    <div class="form-group w-100 mb-3">
        <label for="search" class="d-block mr-2">Pencarian</label>
        <input type="text" name="search" class="form-control w-75 d-inline" id="search" placeholder="Masukkan keyword">
        <button type="submit" class="btn btn-primary mb-1">Cari</button>
    </div>
</form>

<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Hari/jam</th>
        <th>Materi</th>
        <th>Lokasi</th>
        <th>Majelis</th>
        <th>Penyuluh</th>
        <th width="280px">Aksi</th>
    </tr>
    @foreach ($jadwal as $j)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $j->hari_jam }}</td>
        <td>{{ $j->materi }}</td>
        <td>{{ $j->lokasi }}</td>
        <td>{{ $j->majelis->nama_majelis }}</td>
        <td>{{ $j->penyuluh->nama }}</td>
        <td>
            <form action="{{ route('jadwal.destroy',$j->id) }}" method="post">

                <a class="btn btn-info" href="{{ route('jadwal.show',$j->id) }}">Show</a>

                <a class="btn btn-primary" href="{{ route('jadwal.edit',$j->id) }}">Edit</a>

                @csrf
                @method('DELETE')

                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </td>
    </tr>
    @endforeach
</table>

{!! $jadwal->links() !!}


@endsection

latihan/resources/views/jadwal/show.blade.php
@extends('layouts.main')

@section('container')

@if (session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

@if (session()->has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ session('loginError') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
@endif

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Detail Jadwal</h2>
        </div>
        <div class="pull-right mt-4">
            <a class="btn btn-primary" href="{{ route('jadwal.index') }}"> Back</a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>id_penyuluh:</strong>
            {{ $jadwal->id_penyuluh }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>id_majelis:</strong>
            {{ $jadwal->id_majelis }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>penyuluh:</strong>
            {{ $jadwal->penyuluh->nama }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>majelis:</strong>
            {{ $jadwal->majelis->nama_majelis }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Hari Jam :</strong>
            {{ $jadwal->hari_jam }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>materi :</strong>
            {{ $jadwal->materi }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Lokasi :</strong>
            {{ $jadwal->lokasi }}
        </div>
    </div>
</div>

@endsection