latihan/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PenyuluhController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\MajelisController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [HomeController::class, 'home']);

Route::get('/login', [LoginController::class, 'login'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'authenticate']);
Route::post('/logout', [LoginController::class, 'logout']);

Route::get('/register', [RegisterController::class, 'register'])->middleware('guest');
Route::post('/register', [RegisterController::class, 'store']);

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware('auth');

Route::resource('penyuluh', PenyuluhController::class);
Route::get('/penyuluh/search', [PenyuluhController::class, 'search']);

Route::resource('majelis', MajelisController::class);

Route::resource('jadwal', JadwalController::class);

Route::resource('laporan', LaporanController::class);

Route::resource('admin', AdminController::class);

// Route::get('/majelis', [MajelisController::class, 'index'])->name('majelis_view');
// Route::get('/majelis/create', [MajelisController::class, 'create'])->name('majelis_add');
// Route::post('/majelis/create', [MajelisController::class, 'store'])->name('majelis_add');
// Route::get('/user/show/{id}', [MajelisController::class, 'show'])->name('majelis_show');
// Route::post('/user/edit/{id}', 'UserController@edit')->name('user_edit');
// Route::post('/user/delete', 'UserController@delete')->name('user_delete');

// Route::get('/login', [AuthController::class, 'index'])->name('login');
// Route::post('/custom-signin', [AuthController::class, 'createSignin'])->name('signin.custom');


// Route::get('/register', [AuthController::class, 'signup'])->name('register');
// Route::post('/create-user', [AuthController::class, 'customSignup'])->name('user.registration');


// Route::get('/dashboard', [AuthController::class, 'dashboardView'])->name('dashboard');
// Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

latihan/app/Http/Controllers/PenyuluhController.php
<?php

namespace App\Http\Controllers;

use App\Models\PenyuluhModel;
use Illuminate\Http\Request;
use App\Http\Repository\PenyuluhRepository;
use App\Models\User;
use Exception;
use Illuminate\Support\Facades\Hash;
class PenyuluhController extends Controller{

    protected $penyuluhRepo;

    public function __construct()
    {
        $this->penyuluhRepo=new PenyuluhRepository();

    }

    //menampilkan penyuluh
    public function index(Request $request) {

        // dd(request('search'));

        $penyuluh = PenyuluhModel::latest()->with('user')->paginate(5);


        return view('penyuluh.index',[
            "title" => "Penyuluh",
            "active" =>"penyuluh"
        ], compact('penyuluh'))
            ->with('i',(request()->input('page', 1) - 1) * 5);
    }

    public function create() {

        $user = User::all();

        return view ('penyuluh.create',[
            "title" => "Penyuluh",
            "active" =>"penyuluh",
            "users" => $user
        ]);
    }

    public function store(Request $request) {

        $request->validate([
            'nik' => 'required|unique:penyuluh',
            'nama' => 'required',
            'alamat' => 'required',
            'email' => 'required|email|unique:penyuluh',
            'status' => 'required',
            'no_hp' => 'required',
            'tgl_lahir' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'password' => 'required|min:6',
            'level' => 'required',
        ]);

        try {

             // $data = $request->all();
        $user = new User();
        $user->nama = $request->nama;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->level = $request->level;
        $user->save();
        // dump($user);

        $penyuluh = new PenyuluhModel();
        $penyuluh->id_user = $user->id;
        $penyuluh->nama = $user->nama;
        $penyuluh->nik = $request->nik;
        $penyuluh->alamat = $request->alamat;
        $penyuluh->email = $user->email;
        $penyuluh->status = $request->status;
        $penyuluh->no_hp = $request->no_hp;
        $penyuluh->tgl_lahir = $request->tgl_lahir;


        if ($image = $request->file('image')) {
            $destinationPath = 'image/';
            $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            // $data['image'] = "$profileImage";
            $penyuluh->image = "$profileImage";
        }
        $penyuluh->save();
        // dump($penyuluh);
        // dd('test');
        // $check = $this->penyuluhRepo->createPenyuluh($data);
        return redirect()->route('penyuluh.index')->with('success','Successfully!');

        } catch (Exception $e) {

            // \DB::rollback();

            return redirect()->route('penyuluh.index')->with('error','Failed!');
        }
    }

    public function show(PenyuluhModel $penyuluh) {

        return view ('penyuluh.show',[
            "title" => "Penyuluh",
            "active" =>"penyuluh"
        ], compact('penyuluh'));

    }

    public function edit(PenyuluhModel $penyuluh) {

        return view ('penyuluh.edit',[
            "title" => "Penyuluh",
            "active" =>"penyuluh",
        ], compact('penyuluh'));

    }

    public function update(Request $request, PenyuluhModel $penyuluh) {

        //

        $request->validate([
            'nama' => 'required',
            'alamat' => 'required',
            'email' => 'required|email',
            'status' => 'required',
            'no_hp' => 'required',
            'tgl_lahir' => 'required',
        ]);

        $dataPenyuluh = [
            'nama' => $request->nama,
            'alamat'=>$request->alamat,
            'email'=>$request->email,
            'status'=>$request->status,
            'no_hp' => $request->no_hp,
            'tgl_lahir' => $request->tgl_lahir,

        ];

        $penyuluh->update($dataPenyuluh);

        $dataUser = [
            'nama' => $request->nama,
            'email'=>$request->email,
            'password'=>Hash::make($request->password),
            'level'=>$request->level,
        ];

        User::where('id', $penyuluh->id_user)->update($dataUser);

        // $user = new User();
        // $user->nama = $request->nama;
        // $user->email = $request->email;
        // $user->password = Hash::make($request->password);
        // $user->level = $request->level;

        // $penyuluh = new PenyuluhModel();
        // $penyuluh->id_user = $user->id;
        // $penyuluh->nama = $user->nama;
        // $penyuluh->nik = $request->nik;
        // $penyuluh->alamat = $request->alamat;
        // $penyuluh->email = $user->email;
        // $penyuluh->status = $request->status;
        // $penyuluh->no_hp = $request->no_hp;
        // $penyuluh->tgl_lahir = $request->tgl_lahir;

        // if ($image = $request->file('image')) {
        //     $destinationPath = 'image/';
        //     $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
        //     $image->move($destinationPath, $profileImage);
        //     $penyuluh->image = "$profileImage";
        // }else{
        //     unset($penyuluh->image);
        // }

        // $penyuluh->user()->save();
        // $check = $this->penyuluhRepo->updatePenyuluh($data);
        return redirect()->route('penyuluh.index')->with('success','Successfully!');

    }

    public function destroy (PenyuluhModel $penyuluh) {

        $penyuluh->user()->delete();
        return redirect()->route('penyuluh.index')->with('success','Successfully!');
    }

    public function search(Request $request){

        $keyword = $request->search;
        $penyuluh = PenyuluhModel::where('alamat', 'like', "%" . $keyword . "%")->orWhere('nama', 'like', "%" . $keyword . "%")->orWhere('nik', 'like', "%" . $keyword . "%")->orWhere('status', 'like', "%" . $keyword . "%")->orWhere('no_hp', 'like', "%" . $keyword . "%")->paginate(5);
        return view('penyuluh.index',[
            "title" => "Penyuluh",
            "active" =>"penyuluh"
        ], compact('penyuluh'))
            ->with('i',(request()->input('page', 1) - 1) * 5);

    }

}

latihan/resources/views/penyuluh/create.blade.php
@extends('layouts.main')

@section('container')


    @if (session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    @if (session()->has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ session('loginError') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Tambah Penyuluh</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('penyuluh.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <form action="{{ route('penyuluh.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="row">
            {{-- <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Id User:</strong>
                    <input type="number" name="id_user" class="form-control @error('id-user') is-invalid @enderror" placeholder="id_user" value="{{ old('id-user') }} required">

                    @error('id-user')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror

                </div>
            </div> --}}
            {{-- <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Id User:</strong>
                    <select>
                        @foreach ($users as $u)
                        <option value="{{ $u->id }}"></option>
                        @endforeach
                    </select>
                </div>
            </div> --}}

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Nama:</strong>
                    <input type="text" name="nama" class="form-control" placeholder="nama">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Nik:</strong>
                    <input type="text" name="nik" class="form-control" placeholder="nik">
                </div>
            </div>
            <div class="form-floating">
      <input type="password" name = "password" class="form-control @error('password') is-invalid @enderror" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
      @error('password')
        <div class="invalid-feedback">
          {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-floating">
        <input type="text" name = "level" class="form-control @error('level') is-invalid @enderror" id="level" placeholder="level" value="{{ old('level') }}">
        <label for="level">Level</label>
        @error('level')
        <div class="invalid-feedback">
          {{ $message }}
        </div>
        @enderror
      </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Alamat:</strong>
                    <input type="text" name="alamat" class="form-control" placeholder="alamat">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Email:</strong>
                    <input type="text" name="email" class="form-control" placeholder="email">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Status:</strong>
                    <input type="text" name="status" class="form-control" placeholder="status">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Handphone:</strong>
                    <input type="text" name="no_hp" class="form-control" placeholder="no_hp">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Tanggal Lahir:</strong>
                    <input type="date" name="tgl_lahir" class="form-control" placeholder="tgl_lahir">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Foto:</strong>
                    <img class="img-preview img-fluid">
                    <input type="file" name="image" id ="image" class="form-control" placeholder="image" onchange="previewImage">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center mt-4">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>

<script>
     function previewImage() {
        const image = document.querySelector('#image');
        const imgPreview = document.querySelector('.img-preview');

        imgPreview.style.display ='block';

        const oFReader = new FileReader();
        oFReader.readAsDataURL(image.files[0]);

        oFReader.onload = function(oFREvent){
            imgPreview.src = oFREvent.target.result;
        }
    }
</script>



@endsection

latihan/resources/views/penyuluh/edit.blade.php
@extends('layouts.main')

@section('container')

    @if (session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    @if (session()->has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ session('loginError') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Penyuluh</h2>
        </div>
        <div class="pull-right mt-4">
            <a class="btn btn-primary" href="{{ route('penyuluh.index') }}"> Back</a>
        </div>
    </div>
</div>

<form action="{{ route('penyuluh.update',$penyuluh->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')

     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                {{-- <strong>Id User:</strong> --}}
                <input type="hidden" name="id_user" value="{{ $penyuluh->id_user }}" class="form-control" placeholder="id_user">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama:</strong>
                <input type="text" name="nama"  value="{{ $penyuluh->nama }}" class="form-control" placeholder="nama">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nik:</strong>
                <input type="text" name="nik"  value="{{ $penyuluh->nik }}"class="form-control" placeholder="nik" readonly>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>level:</strong>
                <input type="text" name="level"  value="{{ $penyuluh->user->level }}"class="form-control" placeholder="nik" readonly>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Alamat:</strong>
                <input type="text" name="alamat"  value="{{ $penyuluh->alamat }}"class="form-control" placeholder="alamat">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="text" name="email"  value="{{ $penyuluh->user->email }}"class="form-control" placeholder="email">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Status:</strong>
                <input type="text" name="status"  value="{{ $penyuluh->status }}"class="form-control" placeholder="status">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Handphone:</strong>
                <input type="text" name="no_hp"  value="{{ $penyuluh->no_hp }}"class="form-control" placeholder="no_hp">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Tanggal Lahir:</strong>
                <input type="date" name="tgl_lahir"  value="{{ $penyuluh->tgl_lahir }}" class="form-control" placeholder="tgl_lahir">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Foto:</strong>
                <input type="file" name="image" class="form-control" placeholder="image">
                <img src="/image/{{ $penyuluh->image }}" width="300px">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>

@endsection

latihan/resources/views/penyuluh/index.blade.php
@extends('layouts.main')

@section('container')

@if (session()->has ('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ session('success') }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
@endif

@if (session()->has ('error'))
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{ session('loginError') }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
@endif

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Penyuluh</h2>
        </div>
        <div class="pull-right mt-5 mb-4">
            <a class="btn btn-success" href="{{ route('penyuluh.create') }}"> Tambah</a>
        </div>
    </div>
</div>

<form class="form" method="get" action="/penyuluh/search">
    @csrf
    <div class="form-group w-100 mb-3">
        <label for="search" class="d-block mr-2">Pencarian</label>
        <input type="text" name="search" class="form-control w-75 d-inline" id="search" placeholder="Masukkan keyword">
        <button type="submit" class="btn btn-primary mb-1">Cari</button>
    </div>
</form>

<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Email</th>
        <th>Nama</th>
        <th>Nik</th>
        <th>Tanggal Lahir</th>
        <th>No Hp</th>
        <th>Alamat</th>
        <th>Status</th>
        <th width="280px">Aksi</th>
    </tr>
    @foreach ($penyuluh as $p)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $p->user->email}}</td>
        <td>{{ $p->nama }}</td>
        <td>{{ $p->nik }}</td>
        <td>{{ $p->tgl_lahir }}</td>
        <td>{{ $p->no_hp }}</td>
        <td>{{ $p->alamat }}</td>
        <td>{{ $p->status }}</td>
        <td>
            <form action="{{ route('penyuluh.destroy',$p->id) }}" method="post">

                <a class="btn btn-info" href="{{ route('penyuluh.show',$p->id) }}">Show</a>

                <a class="btn btn-primary" href="{{ route('penyuluh.edit',$p->id) }}">Edit</a>

                @csrf
                @method('DELETE')

                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </td>
    </tr>
    @endforeach
</table>

{!! $penyuluh->links() !!}


@endsection

latihan/resources/views/penyuluh/show.blade.php
@extends('layouts.main')

@section('container')

@if (session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

@if (session()->has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ session('loginError') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
@endif

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Detail Penyuluh</h2>
        </div>
        <div class="pull-right mt-4">
            <a class="btn btn-primary" href="{{ route('penyuluh.index') }}"> Back</a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Id User:</strong>
            {{ $penyuluh->id_user }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Nik:</strong>
            {{ $penyuluh->nik }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>nama:</strong>
            {{ $penyuluh->nama }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>alamat :</strong>
            {{ $penyuluh->alamat  }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>email:</strong>
            {{ $penyuluh->email }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>status:</strong>
            {{ $penyuluh->status }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>no_hp:</strong>
            {{ $penyuluh->no_hp }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>tgl_lahir:</strong>
            {{ $penyuluh->tgl_lahir }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>foto:</strong>
            <img src="/image/{{ $penyuluh->image }}" width="500px">
        </div>
    </div>
</div>

@endsection